const { GoogleGenerativeAI } = require('@google/generative-ai');
const prisma = require('../config/db');

/**
 * Generate a structured health summary for a user across all their documents.
 * Returns a JSON object ready to render as a PDF/printable summary.
 */
async function generateHealthSummary(userId) {
  // 1. Fetch user info
  const user = await prisma.user.findUnique({ where: { id: userId } });

  // 2. Fetch all READY documents
  const documents = await prisma.document.findMany({
    where: { userId, status: 'READY' },
    orderBy: { createdAt: 'desc' },
    select: { id: true, fileName: true, fileType: true, extractedText: true, createdAt: true },
  });

  if (documents.length === 0) {
    throw new Error('No processed documents found to generate summary.');
  }

  // 3. Fetch all health metrics
  const metrics = await prisma.healthMetric.findMany({
    where: { userId },
    orderBy: [{ metricName: 'asc' }, { reportDate: 'asc' }],
  });

  // 4. Build context for Gemini
  const docContext = documents
    .map((d) => {
      const text = d.extractedText?.startsWith('NOT_MEDICAL:')
        ? ''
        : (d.extractedText || '').slice(0, 2000);
      return `[Document: ${d.fileName} — ${new Date(d.createdAt).toLocaleDateString()}]\n${text}`;
    })
    .join('\n\n---\n\n');

  const abnormalMetrics = metrics.filter((m) => m.isAbnormal);
  const criticalMetrics = metrics.filter((m) => m.isCritical);

  const genAI = new GoogleGenerativeAI(process.env.GOOGLE_API_KEY);
  const model = genAI.getGenerativeModel({
    model: process.env.GEMINI_MODEL || 'gemini-2.0-flash',
  });

  const prompt = `You are generating a health summary report for a patient to share with their doctor.

Patient: ${user?.fullName || 'Patient'}
Number of documents: ${documents.length}
Total metrics tracked: ${metrics.length}
Abnormal values: ${abnormalMetrics.length}
Critical values: ${criticalMetrics.length}

Document content:
${docContext}

Abnormal metrics found:
${abnormalMetrics.map((m) => `- ${m.metricName}: ${m.value} ${m.unit || ''} (ref: ${m.refRangeLow ?? '?'}-${m.refRangeHigh ?? '?'}) [${m.isCritical ? 'CRITICAL' : 'ABNORMAL'}]`).join('\n') || 'None'}

Generate a comprehensive health briefing JSON with this exact structure:
{
  "patientName": "name",
  "generatedAt": "ISO datetime",
  "overallStatus": "Good / Needs Attention / Critical",
  "summary": "2-3 sentence health overview in plain language",
  "criticalAlerts": [
    { "metric": "name", "value": "value with unit", "message": "plain-language explanation of why this is urgent" }
  ],
  "abnormalFindings": [
    { "metric": "name", "value": "value with unit", "referenceRange": "low-high unit", "significance": "plain-language explanation" }
  ],
  "normalFindings": ["list of normal key metrics as strings"],
  "medications": [
    { "name": "drug name", "dosage": "dose", "frequency": "how often" }
  ],
  "questionsForDoctor": ["suggested question 1", "suggested question 2", "...up to 5 questions"],
  "disclaimer": "This summary was generated by AI and should not replace professional medical advice."
}

Respond with ONLY the JSON object, no markdown.`;

  const result = await model.generateContent(prompt);
  const text = result.response.text().trim();
  const match = text.match(/\{[\s\S]*\}/);
  if (!match) throw new Error('Failed to generate summary');

  const summary = JSON.parse(match[0]);
  summary.patientName = user?.fullName || 'Patient';
  summary.generatedAt = new Date().toISOString();
  summary.documentCount = documents.length;

  return summary;
}

module.exports = { generateHealthSummary };
